//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicJournal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public int TeacherID { get; set; }
        public int LessonID { get; set; }
        public string Note { get; set; }
        public string Description { get; set; }
    
        public virtual Lesson Lesson { get; set; }
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
